package com.example.demo.entity;

import java.sql.Blob;
import java.sql.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;

@Entity
@Table(name = "MDT_AMEND_REQUEST")
public class mdt_amend_request 
{
	@Id
	@Column(name="UNIQUE_ID")
	private String uniqueId;   
	
	@Column(name="TRANSACTION_TYPE")
	private String TRANSACTION_TYPE; 
	
	@Column(name="OCCURENCE")
	private String OCCURENCE; 
	
	@Column(name="FREQUENCY")
	private String FREQUENCY; 
	
	@Column(name="FIRST_COLLECTION_DATE")
	private Date FIRST_COLLECTION_DATE; 
	
	@Column(name="FINAL_COLLECTION_DATE")
	private Date FINAL_COLLECTION_DATE; 
	
	@Column(name="AMOUNT_TYPE")
	private String AMOUNT_TYPE;   
	
	@Column(name="AMOUNT")
	private String AMOUNT;
	
	@Column(name="CREDITOR_NAME")
	private String CREDITOR_NAME;  
	
	@Column(name="CREDITOR_UTILITY_CODE")
	private String CREDITOR_UTILITY_CODE; 
	
	@Column(name="CREDITOR_IDENTIFICATION")
	private String CREDITOR_IDENTIFICATION;
	
	@Column(name="CREDITOR_IDENTIFICATION_NO")
	private String CREDITOR_IDENTIFICATION_NO;
	
	@Column(name="DEBTOR_NAME")
	private String DEBTOR_NAME;   
	
	@Column(name="DEBTOR_ACCOUNT_NO")
	private String DEBTOR_ACCOUNT_NO; 
	
	@Column(name="DEBTOR_ACCOUNT_TYPE")
	private String DEBTOR_ACCOUNT_TYPE;
	
	@Column(name="DEBTOR_BANK_NAME")
	private String DEBTOR_BANK_NAME;
	
	@Column(name="DEBTOR_IDENTIFICATION")
	private String DEBTOR_IDENTIFICATION; 
	
	@Column(name="UMRN")
	private String UMRN;  
	
	@Column(name="DEBTOR_IDENTIFICATION_NO")
	private String DEBTOR_IDENTIFICATION_NO;  
	
	@Column(name="MDT_REQUEST")
	private String MDT_REQUEST; 
	
	@Column(name="BANK_NAME")
	private String BANK_NAME;   
	
	@Column(name = "JPG_IMAGE")
	@Lob
	private byte[] JPG_IMAGE;
	
	@Column(name = "TIFF_IMAGE")
	@Lob
	private byte[] TIFF_IMAGE;
	
	@Column(name="REASON_CODE")
	private String REASON_CODE;  
	
	@Column(name="CATEGORY_CODE")
	private String CATEGORY_CODE;   
	
	@Column(name="CREDITOR_ACCOUNT_NO")
	private String CREDITOR_ACCOUNT_NO;  
	
	@Column(name="CREDITOR_ACCOUNT_NO_TYPE")
	private String CREDITOR_ACCOUNT_NO_TYPE; 
	
	@Column(name="UNTIL_CANCEL")
	private String UNTIL_CANCEL; 
	
	@Column(name="DEB_EMAILID")
	private String DEB_EMAILID; 
	
	@Column(name="DEB_MOBNO")
	private String DEB_MOBNO; 
	
	@Column(name="DATE_OF_MANDATE")
	private Date DATE_OF_MANDATE; 
	
	@Column(name="TRANSACTION_TYPE_PREV")
	private String TRANSACTION_TYPE_PREV; 
	
	@Column(name="OCCURENCE_PREV")
	private String OCCURENCE_PREV; 
	
	@Column(name="FREQUENCY_PREV")
	private String FREQUENCY_PREV;  
	
	@Column(name="FIRST_COLLECTION_PREV")
	private Date FIRST_COLLECTION_PREV;  
	
	@Column(name="FINAL_COLLECTION_PREV")
	private Date FINAL_COLLECTION_PREV; 
	
	@Column(name="AMOUNT_TYPE_PREV")
	private String AMOUNT_TYPE_PREV; 
	
	@Column(name="AMOUNT_PREV")
	private String AMOUNT_PREV;   
	
	@Column(name="DEBTOR_NAME_PREV")
	private String DEBTOR_NAME_PREV; 
	
	@Column(name="DEBTOR_ACCOUNT_NO_PREV")
	private String DEBTOR_ACCOUNT_NO_PREV;
	
	@Column(name="DEBTOR_ACCOUNT_TYPE_PREV")
	private String DEBTOR_ACCOUNT_TYPE_PREV;
	
	@Column(name="DEBTOR_BANK_NAME_PREV")
	private String DEBTOR_BANK_NAME_PREV; 
	
	@Column(name="DEBTOR_IDENTIFICATION_PREV")
	private String DEBTOR_IDENTIFICATION_PREV; 
	
	@Column(name="DEBTOR_IDENT_NO_PREV")
	private String DEBTOR_IDENT_NO_PREV; 
	
	@Column(name="CREDITOR_NAME_PREV")
	private String CREDITOR_NAME_PREV;  
	
	@Column(name="CREDITOR_UTILITY_CODE_PREV")
	private String CREDITOR_UTILITY_CODE_PREV;
	
	@Column(name="CREDITOR_IDENTIFICATION_PREV")
	private String CREDITOR_IDENTIFICATION_PREV;
	
	@Column(name="CREDITOR_IDENT_NO_PREV")
	private String CREDITOR_IDENT_NO_PREV; 
	
	@Column(name="CREATION_DATE_PREV")
	private Date CREATION_DATE_PREV;  
	
	@Column(name="LAST_MODIFIED_PREV")
	private Date LAST_MODIFIED_PREV;
	
	@Column(name = "JPG_IMAGE_PREV")
	@Lob
	private byte[] JPG_IMAGE_PREV;
	
	@Column(name = "TIFF_IMAGE_PREV")
	@Lob
	private byte[] TIFF_IMAGE_PREV;
	
	@Column(name="CATEGORY_CODE_PREV")
	private String CATEGORY_CODE_PREV; 
	
	@Column(name="CREDITOR_ACCOUNT_NO_PREV")
	private String CREDITOR_ACCOUNT_NO_PREV;  
	
	@Column(name="CREDITOR_ACCOUNT_NO_TYPE_PREV")
	private String CREDITOR_ACCOUNT_NO_TYPE_PREV;
	
	@Column(name="UNTIL_CANCEL_PREV")
	private String UNTIL_CANCEL_PREV; 
	
	@Column(name="DEB_EMAILID_PREV")
	private String DEB_EMAILID_PREV;
	
	@Column(name="DEB_MOBNO_PREV")
	private String DEB_MOBNO_PREV; 
	
	@Column(name="DATE_OF_MANDATE_PREV")
	private Date DATE_OF_MANDATE_PREV;
	
	@Column(name="REASON_CODE_PREV")
	private String REASON_CODE_PREV;
	
	@Column(name="LAST_MODIFIED_DATE")
	private Date LAST_MODIFIED_DATE; 
	
	@Column(name="CREATION_DATE")
	private Date CREATION_DATE;

	public String getUniqueId() {
		return uniqueId;
	}

	public String getTRANSACTION_TYPE() {
		return TRANSACTION_TYPE;
	}

	public String getOCCURENCE() {
		return OCCURENCE;
	}

	public String getFREQUENCY() {
		return FREQUENCY;
	}

	public Date getFIRST_COLLECTION_DATE() {
		return FIRST_COLLECTION_DATE;
	}

	public Date getFINAL_COLLECTION_DATE() {
		return FINAL_COLLECTION_DATE;
	}

	public String getAMOUNT_TYPE() {
		return AMOUNT_TYPE;
	}

	public String getAMOUNT() {
		return AMOUNT;
	}

	public String getCREDITOR_NAME() {
		return CREDITOR_NAME;
	}

	public String getCREDITOR_UTILITY_CODE() {
		return CREDITOR_UTILITY_CODE;
	}

	public String getCREDITOR_IDENTIFICATION() {
		return CREDITOR_IDENTIFICATION;
	}

	public String getCREDITOR_IDENTIFICATION_NO() {
		return CREDITOR_IDENTIFICATION_NO;
	}

	public String getDEBTOR_NAME() {
		return DEBTOR_NAME;
	}

	public String getDEBTOR_ACCOUNT_NO() {
		return DEBTOR_ACCOUNT_NO;
	}

	public String getDEBTOR_ACCOUNT_TYPE() {
		return DEBTOR_ACCOUNT_TYPE;
	}

	public String getDEBTOR_BANK_NAME() {
		return DEBTOR_BANK_NAME;
	}

	public String getDEBTOR_IDENTIFICATION() {
		return DEBTOR_IDENTIFICATION;
	}

	public String getUMRN() {
		return UMRN;
	}

	public String getDEBTOR_IDENTIFICATION_NO() {
		return DEBTOR_IDENTIFICATION_NO;
	}

	public String getMDT_REQUEST() {
		return MDT_REQUEST;
	}

	public String getBANK_NAME() {
		return BANK_NAME;
	}

	public byte[] getJPG_IMAGE() {
		return JPG_IMAGE;
	}

	public byte[] getTIFF_IMAGE() {
		return TIFF_IMAGE;
	}

	public String getREASON_CODE() {
		return REASON_CODE;
	}

	public String getCATEGORY_CODE() {
		return CATEGORY_CODE;
	}

	public String getCREDITOR_ACCOUNT_NO() {
		return CREDITOR_ACCOUNT_NO;
	}

	public String getCREDITOR_ACCOUNT_NO_TYPE() {
		return CREDITOR_ACCOUNT_NO_TYPE;
	}

	public String getUNTIL_CANCEL() {
		return UNTIL_CANCEL;
	}

	public String getDEB_EMAILID() {
		return DEB_EMAILID;
	}

	public String getDEB_MOBNO() {
		return DEB_MOBNO;
	}

	public Date getDATE_OF_MANDATE() {
		return DATE_OF_MANDATE;
	}

	public String getTRANSACTION_TYPE_PREV() {
		return TRANSACTION_TYPE_PREV;
	}

	public String getOCCURENCE_PREV() {
		return OCCURENCE_PREV;
	}

	public String getFREQUENCY_PREV() {
		return FREQUENCY_PREV;
	}

	public Date getFIRST_COLLECTION_PREV() {
		return FIRST_COLLECTION_PREV;
	}

	public Date getFINAL_COLLECTION_PREV() {
		return FINAL_COLLECTION_PREV;
	}

	public String getAMOUNT_TYPE_PREV() {
		return AMOUNT_TYPE_PREV;
	}

	public String getAMOUNT_PREV() {
		return AMOUNT_PREV;
	}

	public String getDEBTOR_NAME_PREV() {
		return DEBTOR_NAME_PREV;
	}

	public String getDEBTOR_ACCOUNT_NO_PREV() {
		return DEBTOR_ACCOUNT_NO_PREV;
	}

	public String getDEBTOR_ACCOUNT_TYPE_PREV() {
		return DEBTOR_ACCOUNT_TYPE_PREV;
	}

	public String getDEBTOR_BANK_NAME_PREV() {
		return DEBTOR_BANK_NAME_PREV;
	}

	public String getDEBTOR_IDENTIFICATION_PREV() {
		return DEBTOR_IDENTIFICATION_PREV;
	}

	public String getDEBTOR_IDENT_NO_PREV() {
		return DEBTOR_IDENT_NO_PREV;
	}

	public String getCREDITOR_NAME_PREV() {
		return CREDITOR_NAME_PREV;
	}

	public String getCREDITOR_UTILITY_CODE_PREV() {
		return CREDITOR_UTILITY_CODE_PREV;
	}

	public String getCREDITOR_IDENTIFICATION_PREV() {
		return CREDITOR_IDENTIFICATION_PREV;
	}

	public String getCREDITOR_IDENT_NO_PREV() {
		return CREDITOR_IDENT_NO_PREV;
	}

	public Date getCREATION_DATE_PREV() {
		return CREATION_DATE_PREV;
	}

	public Date getLAST_MODIFIED_PREV() {
		return LAST_MODIFIED_PREV;
	}

	public byte[] getJPG_IMAGE_PREV() {
		return JPG_IMAGE_PREV;
	}

	public byte[] getTIFF_IMAGE_PREV() {
		return TIFF_IMAGE_PREV;
	}

	public String getCATEGORY_CODE_PREV() {
		return CATEGORY_CODE_PREV;
	}

	public String getCREDITOR_ACCOUNT_NO_PREV() {
		return CREDITOR_ACCOUNT_NO_PREV;
	}

	public String getCREDITOR_ACCOUNT_NO_TYPE_PREV() {
		return CREDITOR_ACCOUNT_NO_TYPE_PREV;
	}

	public String getUNTIL_CANCEL_PREV() {
		return UNTIL_CANCEL_PREV;
	}

	public String getDEB_EMAILID_PREV() {
		return DEB_EMAILID_PREV;
	}

	public String getDEB_MOBNO_PREV() {
		return DEB_MOBNO_PREV;
	}

	public Date getDATE_OF_MANDATE_PREV() {
		return DATE_OF_MANDATE_PREV;
	}

	public String getREASON_CODE_PREV() {
		return REASON_CODE_PREV;
	}

	public Date getLAST_MODIFIED_DATE() {
		return LAST_MODIFIED_DATE;
	}

	public Date getCREATION_DATE() {
		return CREATION_DATE;
	}

	public void setUniqueId(String uniqueId) {
		this.uniqueId = uniqueId;
	}

	public void setTRANSACTION_TYPE(String tRANSACTION_TYPE) {
		TRANSACTION_TYPE = tRANSACTION_TYPE;
	}

	public void setOCCURENCE(String oCCURENCE) {
		OCCURENCE = oCCURENCE;
	}

	public void setFREQUENCY(String fREQUENCY) {
		FREQUENCY = fREQUENCY;
	}

	public void setFIRST_COLLECTION_DATE(Date fIRST_COLLECTION_DATE) {
		FIRST_COLLECTION_DATE = fIRST_COLLECTION_DATE;
	}

	public void setFINAL_COLLECTION_DATE(Date fINAL_COLLECTION_DATE) {
		FINAL_COLLECTION_DATE = fINAL_COLLECTION_DATE;
	}

	public void setAMOUNT_TYPE(String aMOUNT_TYPE) {
		AMOUNT_TYPE = aMOUNT_TYPE;
	}

	public void setAMOUNT(String aMOUNT) {
		AMOUNT = aMOUNT;
	}

	public void setCREDITOR_NAME(String cREDITOR_NAME) {
		CREDITOR_NAME = cREDITOR_NAME;
	}

	public void setCREDITOR_UTILITY_CODE(String cREDITOR_UTILITY_CODE) {
		CREDITOR_UTILITY_CODE = cREDITOR_UTILITY_CODE;
	}

	public void setCREDITOR_IDENTIFICATION(String cREDITOR_IDENTIFICATION) {
		CREDITOR_IDENTIFICATION = cREDITOR_IDENTIFICATION;
	}

	public void setCREDITOR_IDENTIFICATION_NO(String cREDITOR_IDENTIFICATION_NO) {
		CREDITOR_IDENTIFICATION_NO = cREDITOR_IDENTIFICATION_NO;
	}

	public void setDEBTOR_NAME(String dEBTOR_NAME) {
		DEBTOR_NAME = dEBTOR_NAME;
	}

	public void setDEBTOR_ACCOUNT_NO(String dEBTOR_ACCOUNT_NO) {
		DEBTOR_ACCOUNT_NO = dEBTOR_ACCOUNT_NO;
	}

	public void setDEBTOR_ACCOUNT_TYPE(String dEBTOR_ACCOUNT_TYPE) {
		DEBTOR_ACCOUNT_TYPE = dEBTOR_ACCOUNT_TYPE;
	}

	public void setDEBTOR_BANK_NAME(String dEBTOR_BANK_NAME) {
		DEBTOR_BANK_NAME = dEBTOR_BANK_NAME;
	}

	public void setDEBTOR_IDENTIFICATION(String dEBTOR_IDENTIFICATION) {
		DEBTOR_IDENTIFICATION = dEBTOR_IDENTIFICATION;
	}

	public void setUMRN(String uMRN) {
		UMRN = uMRN;
	}

	public void setDEBTOR_IDENTIFICATION_NO(String dEBTOR_IDENTIFICATION_NO) {
		DEBTOR_IDENTIFICATION_NO = dEBTOR_IDENTIFICATION_NO;
	}

	public void setMDT_REQUEST(String mDT_REQUEST) {
		MDT_REQUEST = mDT_REQUEST;
	}

	public void setBANK_NAME(String bANK_NAME) {
		BANK_NAME = bANK_NAME;
	}

	public void setJPG_IMAGE(byte[] jPG_IMAGE) {
		JPG_IMAGE = jPG_IMAGE;
	}

	public void setTIFF_IMAGE(byte[] tIFF_IMAGE) {
		TIFF_IMAGE = tIFF_IMAGE;
	}

	public void setREASON_CODE(String rEASON_CODE) {
		REASON_CODE = rEASON_CODE;
	}

	public void setCATEGORY_CODE(String cATEGORY_CODE) {
		CATEGORY_CODE = cATEGORY_CODE;
	}

	public void setCREDITOR_ACCOUNT_NO(String cREDITOR_ACCOUNT_NO) {
		CREDITOR_ACCOUNT_NO = cREDITOR_ACCOUNT_NO;
	}

	public void setCREDITOR_ACCOUNT_NO_TYPE(String cREDITOR_ACCOUNT_NO_TYPE) {
		CREDITOR_ACCOUNT_NO_TYPE = cREDITOR_ACCOUNT_NO_TYPE;
	}

	public void setUNTIL_CANCEL(String uNTIL_CANCEL) {
		UNTIL_CANCEL = uNTIL_CANCEL;
	}

	public void setDEB_EMAILID(String dEB_EMAILID) {
		DEB_EMAILID = dEB_EMAILID;
	}

	public void setDEB_MOBNO(String dEB_MOBNO) {
		DEB_MOBNO = dEB_MOBNO;
	}

	public void setDATE_OF_MANDATE(Date dATE_OF_MANDATE) {
		DATE_OF_MANDATE = dATE_OF_MANDATE;
	}

	public void setTRANSACTION_TYPE_PREV(String tRANSACTION_TYPE_PREV) {
		TRANSACTION_TYPE_PREV = tRANSACTION_TYPE_PREV;
	}

	public void setOCCURENCE_PREV(String oCCURENCE_PREV) {
		OCCURENCE_PREV = oCCURENCE_PREV;
	}

	public void setFREQUENCY_PREV(String fREQUENCY_PREV) {
		FREQUENCY_PREV = fREQUENCY_PREV;
	}

	public void setFIRST_COLLECTION_PREV(Date fIRST_COLLECTION_PREV) {
		FIRST_COLLECTION_PREV = fIRST_COLLECTION_PREV;
	}

	public void setFINAL_COLLECTION_PREV(Date fINAL_COLLECTION_PREV) {
		FINAL_COLLECTION_PREV = fINAL_COLLECTION_PREV;
	}

	public void setAMOUNT_TYPE_PREV(String aMOUNT_TYPE_PREV) {
		AMOUNT_TYPE_PREV = aMOUNT_TYPE_PREV;
	}

	public void setAMOUNT_PREV(String aMOUNT_PREV) {
		AMOUNT_PREV = aMOUNT_PREV;
	}

	public void setDEBTOR_NAME_PREV(String dEBTOR_NAME_PREV) {
		DEBTOR_NAME_PREV = dEBTOR_NAME_PREV;
	}

	public void setDEBTOR_ACCOUNT_NO_PREV(String dEBTOR_ACCOUNT_NO_PREV) {
		DEBTOR_ACCOUNT_NO_PREV = dEBTOR_ACCOUNT_NO_PREV;
	}

	public void setDEBTOR_ACCOUNT_TYPE_PREV(String dEBTOR_ACCOUNT_TYPE_PREV) {
		DEBTOR_ACCOUNT_TYPE_PREV = dEBTOR_ACCOUNT_TYPE_PREV;
	}

	public void setDEBTOR_BANK_NAME_PREV(String dEBTOR_BANK_NAME_PREV) {
		DEBTOR_BANK_NAME_PREV = dEBTOR_BANK_NAME_PREV;
	}

	public void setDEBTOR_IDENTIFICATION_PREV(String dEBTOR_IDENTIFICATION_PREV) {
		DEBTOR_IDENTIFICATION_PREV = dEBTOR_IDENTIFICATION_PREV;
	}

	public void setDEBTOR_IDENT_NO_PREV(String dEBTOR_IDENT_NO_PREV) {
		DEBTOR_IDENT_NO_PREV = dEBTOR_IDENT_NO_PREV;
	}

	public void setCREDITOR_NAME_PREV(String cREDITOR_NAME_PREV) {
		CREDITOR_NAME_PREV = cREDITOR_NAME_PREV;
	}

	public void setCREDITOR_UTILITY_CODE_PREV(String cREDITOR_UTILITY_CODE_PREV) {
		CREDITOR_UTILITY_CODE_PREV = cREDITOR_UTILITY_CODE_PREV;
	}

	public void setCREDITOR_IDENTIFICATION_PREV(String cREDITOR_IDENTIFICATION_PREV) {
		CREDITOR_IDENTIFICATION_PREV = cREDITOR_IDENTIFICATION_PREV;
	}

	public void setCREDITOR_IDENT_NO_PREV(String cREDITOR_IDENT_NO_PREV) {
		CREDITOR_IDENT_NO_PREV = cREDITOR_IDENT_NO_PREV;
	}

	public void setCREATION_DATE_PREV(Date cREATION_DATE_PREV) {
		CREATION_DATE_PREV = cREATION_DATE_PREV;
	}

	public void setLAST_MODIFIED_PREV(Date lAST_MODIFIED_PREV) {
		LAST_MODIFIED_PREV = lAST_MODIFIED_PREV;
	}

	public void setJPG_IMAGE_PREV(byte[] jPG_IMAGE_PREV) {
		JPG_IMAGE_PREV = jPG_IMAGE_PREV;
	}

	public void setTIFF_IMAGE_PREV(byte[] tIFF_IMAGE_PREV) {
		TIFF_IMAGE_PREV = tIFF_IMAGE_PREV;
	}

	public void setCATEGORY_CODE_PREV(String cATEGORY_CODE_PREV) {
		CATEGORY_CODE_PREV = cATEGORY_CODE_PREV;
	}

	public void setCREDITOR_ACCOUNT_NO_PREV(String cREDITOR_ACCOUNT_NO_PREV) {
		CREDITOR_ACCOUNT_NO_PREV = cREDITOR_ACCOUNT_NO_PREV;
	}

	public void setCREDITOR_ACCOUNT_NO_TYPE_PREV(String cREDITOR_ACCOUNT_NO_TYPE_PREV) {
		CREDITOR_ACCOUNT_NO_TYPE_PREV = cREDITOR_ACCOUNT_NO_TYPE_PREV;
	}

	public void setUNTIL_CANCEL_PREV(String uNTIL_CANCEL_PREV) {
		UNTIL_CANCEL_PREV = uNTIL_CANCEL_PREV;
	}

	public void setDEB_EMAILID_PREV(String dEB_EMAILID_PREV) {
		DEB_EMAILID_PREV = dEB_EMAILID_PREV;
	}

	public void setDEB_MOBNO_PREV(String dEB_MOBNO_PREV) {
		DEB_MOBNO_PREV = dEB_MOBNO_PREV;
	}

	public void setDATE_OF_MANDATE_PREV(Date dATE_OF_MANDATE_PREV) {
		DATE_OF_MANDATE_PREV = dATE_OF_MANDATE_PREV;
	}

	public void setREASON_CODE_PREV(String rEASON_CODE_PREV) {
		REASON_CODE_PREV = rEASON_CODE_PREV;
	}

	public void setLAST_MODIFIED_DATE(Date lAST_MODIFIED_DATE) {
		LAST_MODIFIED_DATE = lAST_MODIFIED_DATE;
	}

	public void setCREATION_DATE(Date cREATION_DATE) {
		CREATION_DATE = cREATION_DATE;
	}

	public mdt_amend_request(String uniqueId, String tRANSACTION_TYPE, String oCCURENCE, String fREQUENCY,
			Date fIRST_COLLECTION_DATE, Date fINAL_COLLECTION_DATE, String aMOUNT_TYPE, String aMOUNT,
			String cREDITOR_NAME, String cREDITOR_UTILITY_CODE, String cREDITOR_IDENTIFICATION,
			String cREDITOR_IDENTIFICATION_NO, String dEBTOR_NAME, String dEBTOR_ACCOUNT_NO, String dEBTOR_ACCOUNT_TYPE,
			String dEBTOR_BANK_NAME, String dEBTOR_IDENTIFICATION, String uMRN, String dEBTOR_IDENTIFICATION_NO,
			String mDT_REQUEST, String bANK_NAME, byte[] jPG_IMAGE, byte[] tIFF_IMAGE, String rEASON_CODE,
			String cATEGORY_CODE, String cREDITOR_ACCOUNT_NO, String cREDITOR_ACCOUNT_NO_TYPE, String uNTIL_CANCEL,
			String dEB_EMAILID, String dEB_MOBNO, Date dATE_OF_MANDATE, String tRANSACTION_TYPE_PREV,
			String oCCURENCE_PREV, String fREQUENCY_PREV, Date fIRST_COLLECTION_PREV, Date fINAL_COLLECTION_PREV,
			String aMOUNT_TYPE_PREV, String aMOUNT_PREV, String dEBTOR_NAME_PREV, String dEBTOR_ACCOUNT_NO_PREV,
			String dEBTOR_ACCOUNT_TYPE_PREV, String dEBTOR_BANK_NAME_PREV, String dEBTOR_IDENTIFICATION_PREV,
			String dEBTOR_IDENT_NO_PREV, String cREDITOR_NAME_PREV, String cREDITOR_UTILITY_CODE_PREV,
			String cREDITOR_IDENTIFICATION_PREV, String cREDITOR_IDENT_NO_PREV, Date cREATION_DATE_PREV,
			Date lAST_MODIFIED_PREV, byte[] jPG_IMAGE_PREV, byte[] tIFF_IMAGE_PREV, String cATEGORY_CODE_PREV,
			String cREDITOR_ACCOUNT_NO_PREV, String cREDITOR_ACCOUNT_NO_TYPE_PREV, String uNTIL_CANCEL_PREV,
			String dEB_EMAILID_PREV, String dEB_MOBNO_PREV, Date dATE_OF_MANDATE_PREV, String rEASON_CODE_PREV,
			Date lAST_MODIFIED_DATE, Date cREATION_DATE) {
		super();
		this.uniqueId = uniqueId;
		TRANSACTION_TYPE = tRANSACTION_TYPE;
		OCCURENCE = oCCURENCE;
		FREQUENCY = fREQUENCY;
		FIRST_COLLECTION_DATE = fIRST_COLLECTION_DATE;
		FINAL_COLLECTION_DATE = fINAL_COLLECTION_DATE;
		AMOUNT_TYPE = aMOUNT_TYPE;
		AMOUNT = aMOUNT;
		CREDITOR_NAME = cREDITOR_NAME;
		CREDITOR_UTILITY_CODE = cREDITOR_UTILITY_CODE;
		CREDITOR_IDENTIFICATION = cREDITOR_IDENTIFICATION;
		CREDITOR_IDENTIFICATION_NO = cREDITOR_IDENTIFICATION_NO;
		DEBTOR_NAME = dEBTOR_NAME;
		DEBTOR_ACCOUNT_NO = dEBTOR_ACCOUNT_NO;
		DEBTOR_ACCOUNT_TYPE = dEBTOR_ACCOUNT_TYPE;
		DEBTOR_BANK_NAME = dEBTOR_BANK_NAME;
		DEBTOR_IDENTIFICATION = dEBTOR_IDENTIFICATION;
		UMRN = uMRN;
		DEBTOR_IDENTIFICATION_NO = dEBTOR_IDENTIFICATION_NO;
		MDT_REQUEST = mDT_REQUEST;
		BANK_NAME = bANK_NAME;
		JPG_IMAGE = jPG_IMAGE;
		TIFF_IMAGE = tIFF_IMAGE;
		REASON_CODE = rEASON_CODE;
		CATEGORY_CODE = cATEGORY_CODE;
		CREDITOR_ACCOUNT_NO = cREDITOR_ACCOUNT_NO;
		CREDITOR_ACCOUNT_NO_TYPE = cREDITOR_ACCOUNT_NO_TYPE;
		UNTIL_CANCEL = uNTIL_CANCEL;
		DEB_EMAILID = dEB_EMAILID;
		DEB_MOBNO = dEB_MOBNO;
		DATE_OF_MANDATE = dATE_OF_MANDATE;
		TRANSACTION_TYPE_PREV = tRANSACTION_TYPE_PREV;
		OCCURENCE_PREV = oCCURENCE_PREV;
		FREQUENCY_PREV = fREQUENCY_PREV;
		FIRST_COLLECTION_PREV = fIRST_COLLECTION_PREV;
		FINAL_COLLECTION_PREV = fINAL_COLLECTION_PREV;
		AMOUNT_TYPE_PREV = aMOUNT_TYPE_PREV;
		AMOUNT_PREV = aMOUNT_PREV;
		DEBTOR_NAME_PREV = dEBTOR_NAME_PREV;
		DEBTOR_ACCOUNT_NO_PREV = dEBTOR_ACCOUNT_NO_PREV;
		DEBTOR_ACCOUNT_TYPE_PREV = dEBTOR_ACCOUNT_TYPE_PREV;
		DEBTOR_BANK_NAME_PREV = dEBTOR_BANK_NAME_PREV;
		DEBTOR_IDENTIFICATION_PREV = dEBTOR_IDENTIFICATION_PREV;
		DEBTOR_IDENT_NO_PREV = dEBTOR_IDENT_NO_PREV;
		CREDITOR_NAME_PREV = cREDITOR_NAME_PREV;
		CREDITOR_UTILITY_CODE_PREV = cREDITOR_UTILITY_CODE_PREV;
		CREDITOR_IDENTIFICATION_PREV = cREDITOR_IDENTIFICATION_PREV;
		CREDITOR_IDENT_NO_PREV = cREDITOR_IDENT_NO_PREV;
		CREATION_DATE_PREV = cREATION_DATE_PREV;
		LAST_MODIFIED_PREV = lAST_MODIFIED_PREV;
		JPG_IMAGE_PREV = jPG_IMAGE_PREV;
		TIFF_IMAGE_PREV = tIFF_IMAGE_PREV;
		CATEGORY_CODE_PREV = cATEGORY_CODE_PREV;
		CREDITOR_ACCOUNT_NO_PREV = cREDITOR_ACCOUNT_NO_PREV;
		CREDITOR_ACCOUNT_NO_TYPE_PREV = cREDITOR_ACCOUNT_NO_TYPE_PREV;
		UNTIL_CANCEL_PREV = uNTIL_CANCEL_PREV;
		DEB_EMAILID_PREV = dEB_EMAILID_PREV;
		DEB_MOBNO_PREV = dEB_MOBNO_PREV;
		DATE_OF_MANDATE_PREV = dATE_OF_MANDATE_PREV;
		REASON_CODE_PREV = rEASON_CODE_PREV;
		LAST_MODIFIED_DATE = lAST_MODIFIED_DATE;
		CREATION_DATE = cREATION_DATE;
	}

	public mdt_amend_request() {
		super();
		// TODO Auto-generated constructor stub
	}

	@Override
	public String toString() {
		return "mdt_amend_request [uniqueId=" + uniqueId + ", TRANSACTION_TYPE=" + TRANSACTION_TYPE + ", OCCURENCE="
				+ OCCURENCE + ", FREQUENCY=" + FREQUENCY + ", FIRST_COLLECTION_DATE=" + FIRST_COLLECTION_DATE
				+ ", FINAL_COLLECTION_DATE=" + FINAL_COLLECTION_DATE + ", AMOUNT_TYPE=" + AMOUNT_TYPE + ", AMOUNT="
				+ AMOUNT + ", CREDITOR_NAME=" + CREDITOR_NAME + ", CREDITOR_UTILITY_CODE=" + CREDITOR_UTILITY_CODE
				+ ", CREDITOR_IDENTIFICATION=" + CREDITOR_IDENTIFICATION + ", CREDITOR_IDENTIFICATION_NO="
				+ CREDITOR_IDENTIFICATION_NO + ", DEBTOR_NAME=" + DEBTOR_NAME + ", DEBTOR_ACCOUNT_NO="
				+ DEBTOR_ACCOUNT_NO + ", DEBTOR_ACCOUNT_TYPE=" + DEBTOR_ACCOUNT_TYPE + ", DEBTOR_BANK_NAME="
				+ DEBTOR_BANK_NAME + ", DEBTOR_IDENTIFICATION=" + DEBTOR_IDENTIFICATION + ", UMRN=" + UMRN
				+ ", DEBTOR_IDENTIFICATION_NO=" + DEBTOR_IDENTIFICATION_NO + ", MDT_REQUEST=" + MDT_REQUEST
				+ ", BANK_NAME=" + BANK_NAME + ", REASON_CODE=" + REASON_CODE + ", CATEGORY_CODE=" + CATEGORY_CODE
				+ ", CREDITOR_ACCOUNT_NO=" + CREDITOR_ACCOUNT_NO + ", CREDITOR_ACCOUNT_NO_TYPE="
				+ CREDITOR_ACCOUNT_NO_TYPE + ", UNTIL_CANCEL=" + UNTIL_CANCEL + ", DEB_EMAILID=" + DEB_EMAILID
				+ ", DEB_MOBNO=" + DEB_MOBNO + ", DATE_OF_MANDATE=" + DATE_OF_MANDATE + ", TRANSACTION_TYPE_PREV="
				+ TRANSACTION_TYPE_PREV + ", OCCURENCE_PREV=" + OCCURENCE_PREV + ", FREQUENCY_PREV=" + FREQUENCY_PREV
				+ ", FIRST_COLLECTION_PREV=" + FIRST_COLLECTION_PREV + ", FINAL_COLLECTION_PREV="
				+ FINAL_COLLECTION_PREV + ", AMOUNT_TYPE_PREV=" + AMOUNT_TYPE_PREV + ", AMOUNT_PREV=" + AMOUNT_PREV
				+ ", DEBTOR_NAME_PREV=" + DEBTOR_NAME_PREV + ", DEBTOR_ACCOUNT_NO_PREV=" + DEBTOR_ACCOUNT_NO_PREV
				+ ", DEBTOR_ACCOUNT_TYPE_PREV=" + DEBTOR_ACCOUNT_TYPE_PREV + ", DEBTOR_BANK_NAME_PREV="
				+ DEBTOR_BANK_NAME_PREV + ", DEBTOR_IDENTIFICATION_PREV=" + DEBTOR_IDENTIFICATION_PREV
				+ ", DEBTOR_IDENT_NO_PREV=" + DEBTOR_IDENT_NO_PREV + ", CREDITOR_NAME_PREV=" + CREDITOR_NAME_PREV
				+ ", CREDITOR_UTILITY_CODE_PREV=" + CREDITOR_UTILITY_CODE_PREV + ", CREDITOR_IDENTIFICATION_PREV="
				+ CREDITOR_IDENTIFICATION_PREV + ", CREDITOR_IDENT_NO_PREV=" + CREDITOR_IDENT_NO_PREV
				+ ", CREATION_DATE_PREV=" + CREATION_DATE_PREV + ", LAST_MODIFIED_PREV=" + LAST_MODIFIED_PREV
				+ ", CATEGORY_CODE_PREV=" + CATEGORY_CODE_PREV + ", CREDITOR_ACCOUNT_NO_PREV="
				+ CREDITOR_ACCOUNT_NO_PREV + ", CREDITOR_ACCOUNT_NO_TYPE_PREV=" + CREDITOR_ACCOUNT_NO_TYPE_PREV
				+ ", UNTIL_CANCEL_PREV=" + UNTIL_CANCEL_PREV + ", DEB_EMAILID_PREV=" + DEB_EMAILID_PREV
				+ ", DEB_MOBNO_PREV=" + DEB_MOBNO_PREV + ", DATE_OF_MANDATE_PREV=" + DATE_OF_MANDATE_PREV
				+ ", REASON_CODE_PREV=" + REASON_CODE_PREV + ", LAST_MODIFIED_DATE=" + LAST_MODIFIED_DATE
				+ ", CREATION_DATE=" + CREATION_DATE + "]";
	}
	
	

	

}
